%{
Author:
    Charles
Function:
    Get the gaussian kernel.
Input:
    -sigma: the standard devation.
Output:
    -kernel: 2-D matrix generated by gussian formula.
%}
function kernel = getGK(sigma)
kernel_size = floor(3 * sigma) * 2 + 1;
apply_range = [1: kernel_size] - (kernel_size + 1) / 2;
[x, y] = meshgrid(apply_range);
kernel = 1 / (2 * pi * sigma^2) * exp(-(x.^2 + y.^2) / (2 * sigma^2));
end